/*
 * File: CollectNewspaper.k
 * ------------------------
 * The CollectNewspaper program instructs Karel to walk
 * to the door of its house, pick up the newspaper, and
 * return to its initial position.
 */

import "turns";

/*
 * Collects the newspaper from outside the door and then
 * returns to the starting position.  This function works
 * only for the specific world specified in the exercise.
 */

function collectNewspaper() {
	// You fill this in along with any helper functions
}
